// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID                pgtype.UUID
	HashedKey         string
	WindowSizeSeconds int32
	RequestsPerWindow int32
	CreatedAt         pgtype.Timestamp
}
